spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tFxT2Y1osgr9zoDfcNN
      secret-key: iAizSOmp3EvYD2oArjhpa1bkfoFkmc
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: jjmall
  application:
    name: mall-third-party
server:
  port: 30000